### ISSUE TITLE
Move to EmbeddedUtilities repo

### ISSUE THREAD

**Issue by glencoe** [es-uni-due/EmbeddedUtil#4]
Rename the repo to EmbeddedUtilities.

**Comment by magshee** [comment]
Renaming repo is only possible for owner, not members. Specified another assignee.

**Comment by saphieron** [comment]
Renamed. I guess this can be closed now.

**Comment by magshee** [comment]
In order to work properly, the new URL should be set on local clones. Technically it still works, but if someone creates a repository with the old name, the redirect will break. This can be done by executing the following command in the local repo.
`$ git remote set-url origin new_url`
